version: '2'

services:
  frontend:
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - "8080:8080"
    # volumes:
    #   - "./frontend:/usr/share/nginx/html"
    volumes:
      - ".:/src/app"
