version: '2'

services:
  broadcaster:
    build:
      context: ./broadcaster
    volumes:
      - "./broadcaster:/code"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/broadcaster"
      - "traefik.port=9500"
      - "traefik.backend=broadcaster"

  data-service:
    build:
      dockerfile: Dockerfile-dev
      context: ./data-service
    volumes:
      - "./data-service:/src/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/data-service"
      - "traefik.port=3721"
      - "traefik.backend=data-service"

  redis:
    image: redis:2.8.19
    ports:
      - 6379:6379

  delivery:
    build:
      context: ./delivery
    volumes:
      - "./delivery:/src/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/delivery"
      - "traefik.port=3000"
      - "traefik.backend=delivery"

  frontend:
    build:
      dockerfile: Dockerfile-dev
      context: ./frontend
    ports:
      - "12004:80"
    volumes:
      - "./frontend:/usr/share/nginx/html"

  gamemanager:
    build:
      context: ./gamemanager
      dockerfile: Dockerfile-dev
    volumes:
      - "./gamemanager:/code"
    environment:
     - PYTHONUNBUFFERED=0
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/gamemanager"
      - "traefik.port=5000"
      - "traefik.backend=gamemanager"

  gateway:
    image: traefik:v1.1.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./gateway/dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.backend=gateway"

  physics:
    build:
      context: ./physics
    volumes:
      - "./physics:/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/simulate"
      - "traefik.port=3005"
      - "traefik.backend=physics"

  results:
    build:
      dockerfile: Dockerfile-dev
      context: ./results
    volumes:
      - "./results:/app"
    command: bash -c "cd /app && dotnet restore && dotnet watch run --server.urls http://*:5000"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/results"
      - "traefik.port=5000"
      - "traefik.backend=results"
