version: '2'

services:
  proxy:
    image: traefik:v1.1.2
    ports:
      - "80:80"
    volumes:
      - "./proxy/dev.toml:/etc/traefik/traefik.toml"

  gateway:
    image: traefik:v1.1.2
    ports:
      - "8888:8888"
      - "8088:8088"
    volumes:
      - "./gateway/dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.backend=gateway"

  redis:
    image: redis:2.8.19
    ports:
      - 6379:6379

  broadcaster:
    build:
      context: ./broadcaster
      dockerfile: Dockerfile-dev
    ports:
      - 9999:5000
    volumes:
      - "./broadcaster:/code"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/broadcaster"
      - "traefik.port=5000"
      - "traefik.backend=broadcaster"

  data-service:
    build:
      dockerfile: Dockerfile-dev
      context: ./data-service
    volumes:
      - "./data-service:/src/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/data-service"
      - "traefik.port=3721"
      - "traefik.backend=data-service"

  delivery:
    build:
      context: ./delivery
    volumes:
      - "./delivery:/src/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/delivery"
      - "traefik.port=3000"
      - "traefik.backend=delivery"

  frontend:
    image: nginx:1.11.8-alpine
    ports:
      - "8080:80"
    volumes:
      - "./frontend/index.html:/usr/share/nginx/html/index.html"
      - "./frontend/dist:/usr/share/nginx/html/dist"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/frontend"
      - "traefik.port=80"
      - "traefik.backend=frontend"

  gamemanager:
    build:
      context: ./gamemanager
      dockerfile: Dockerfile-dev
    volumes:
      - "./gamemanager:/code"
    environment:
     - PYTHONUNBUFFERED=0
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/gamemanager"
      - "traefik.port=5000"
      - "traefik.backend=gamemanager"

  scores:
    build:
      context: ./scores
      dockerfile: Dockerfile-dev
    volumes:
      - "./scores:/code"
    environment:
     - PYTHONUNBUFFERED=0
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/scores"
      - "traefik.port=5000"
      - "traefik.backend=scores"

  physics:
    build:
      context: ./physics
      dockerfile: Dockerfile-dev
    volumes:
      - "./physics:/src/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/physics"
      - "traefik.port=3005"
      - "traefik.backend=physics"

  results:
    build:
      dockerfile: Dockerfile-dev
      context: ./results
    volumes:
      - "./results:/app"
    command: bash -c "cd /app && dotnet restore && dotnet watch run --server.urls http://*:5000"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/results"
      - "traefik.port=5000"
      - "traefik.backend=results"
