version: '2'

services:
  delivery:
    build:
      context: ./delivery
    volumes:
      - "./delivery:/src/app"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/delivery"
      - "traefik.port=3000"
      - "traefik.backend=delivery"

  gateway:
    image: traefik:v1.1.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./gateway/dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.backend=gateway"
