version: '2'

services:
  broadcaster:
    build:
      context: ./broadcaster
    ports:
      - 9999:5000
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/broadcaster"
      - "traefik.port=5000"
      - "traefik.backend=broadcaster"

  data-service:
    build:
      context: ./data-service
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/data-service"
      - "traefik.port=3721"
      - "traefik.backend=data-service"

  redis:
    image: redis:2.8.19
    ports:
      - 6379:6379

  delivery:
    build:
      context: ./delivery
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/delivery"
      - "traefik.port=3000"
      - "traefik.backend=delivery"

  frontend:
    build:
      dockerfile: Dockerfile-dev
      context: ./frontend
    ports:
      - "8080:8080"
    # volumes:
    #   - "./frontend:/usr/share/nginx/html"
    volumes:
      - "./frontend:/src/app"


  gamemanager:
    build:
      context: ./gamemanager
    environment:
     - PYTHONUNBUFFERED=0
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/gamemanager"
      - "traefik.port=5000"
      - "traefik.backend=gamemanager"

  scores:
    build:
      context: ./scores
    environment:
     - PYTHONUNBUFFERED=0
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/scores"
      - "traefik.port=5000"
      - "traefik.backend=scores"


  gateway:
    image: traefik:v1.1.2
    ports:
      - "80:80"
      - "8088:8088"
    volumes:
      - "./gateway/prod.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.backend=gateway"

  physics:
    build:
      context: ./physics
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/physics"
      - "traefik.port=3005"
      - "traefik.backend=physics"

  results:
    build:
      context: ./results
    command: bash -c "cd /app && dotnet restore && dotnet watch run --server.urls http://*:5000"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/results"
      - "traefik.port=5000"
      - "traefik.backend=results"
