FROM node:7.5.0-alpine

RUN mkdir /src

RUN npm install gulp -g

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

ADD . /src/app

WORKDIR /src/app

ENV NODE_ENV development

EXPOSE 3721

CMD ["gulp"]
