version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    volumes:
      - ".:/src/app"

  redis:
    image: redis:2.8.19
    ports:
      - 6379:6379
