---
- hosts: prod
  remote_user: ubuntu

  tasks:
    - name: 'fetch source code'
      git:
        repo: https://github.com/alkukampela/curling.git
        dest: ~/curling

    - name: Install frontend dependencies
      shell: npm install
      args:
        chdir: ~/curling/frontend

    - name: Build frontend
      shell: npm run build
      args:
        chdir: ~/curling/frontend

    - name: 'start containers'
      command: docker-compose -f /home/ubuntu/curling/prod.yml up -d --build
