---
- hosts: prod
  remote_user: ubuntu

  tasks:
  - include: tasks/scale.yml service=physics count=2
  - include: tasks/scale.yml service=scores count=2
  - include: tasks/scale.yml service=delivery count=2
  - include: tasks/scale.yml service=games count=2
