FROM mhart/alpine-node:7.3.0

RUN mkdir /src

RUN npm install nodemon -g

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

ADD . /src/app

WORKDIR /src/app

ENV NODE_ENV development

EXPOSE 3005

CMD ["npm", "run", "dev"]
