logLevel = "DEBUG"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]
  watch = true

[backends]
  [backends.gateway]
    [backends.gateway.servers.server1]
    url = "http://gateway:8888"
  [backends.frontend]
    [backends.frontend.servers.server1]
      url = "http://frontend"

[frontends]
  [frontends.gateway]
    backend = "gateway"
    passHostHeader = true
      [frontends.gateway.routes.test_1]
        rule = "Path: /delivery, /gamemanager/begin_game, /gamemanager/join_game, /results, /results/{game_id}, /results/stones/{game_id}"
  [frontends.frontend]
    backend = "frontend"
    passHostHeader = true
      [frontenda.frontends.routes.test_1]
        rule = "Path: /"


# https://docs.traefik.io/basics/#frontends        
