logLevel = "DEBUG"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
    address = ":80"

[file]
  watch = true

[backends]
  [backends.spa]
    [backends.spa.servers.server_1]
      url = "http://frontend:8080"
  [backends.gateway]
    [backends.gateway.servers.server_1]
      url = "http://gateway:8888"
  [backends.broadcaster]
    [backends.broadcaster.servers.server_1]
      url = "http://broadcaster"

[frontends]
  [frontends.spa]
    backend = "spa"
    passHostHeader = true
      [frontends.spa.routes.route_1]
        rule = "Path: /, /dist/{*}"
  [frontends.gateway]
    backend = "gateway"
    passHostHeader = true
      [frontends.gateway.routes.route_1]
        rule = "Path: /delivery, /games/begin, /games/join, /results, /results/{game_id}, /results/stones/{game_id}"
  [frontends.broadcaster]
    backend = "broadcaster"
    passHostHeader = true
      [frontends.broadcaster.routes.route_1]
        rule = "Path: /deliveries/"


################################################################
# Web configuration backend
################################################################
[web]
address = ":8088"
